# Site settings
title: Katja Hollaar
email: afkatja@gmail.com
description: >
  Personal portfolio page
baseurl:
url: "http://afkatja.github.io"
twitter_username: afkatja
github_username:  afkatja
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _scss
include: ['_pages']
kramdown:
  input: GFM

collections:
  - index
  - projects
  - work
  - edu

gems:
  - jekyll-octicons
