export const categoriesFromLabels = {
  Wildlife: [
    "animal",
    "bird",
    "mammal",
    "fish",
    "insect",
    "wildlife",
    "frog",
    "toucan",
  ],
  Portrait: [
    "person",
    "face",
    "selfie",
    "smile",
    "model",
    "portrait",
    "dreadlocks",
  ],
  Landscape: [
    "mountain",
    "river",
    "sky",
    "scenery",
    "landscape",
    "valley",
    "road",
    "sea",
    "beach",
    "ocean",
    "car",
    "vehicle",
  ],
  Architecture: ["building", "city", "bridge", "tower", "architecture"],
  Abstract: ["pattern", "texture", "design", "shape", "abstract"],
}
